algorandfoundation/nodekit

api/lf.go
cmd/root.go
cmd/root_test.go
cmd/status.go
generate.yaml
go.mod
go.sum
internal/metrics.go
internal/status.go
ui/controls.go
ui/controls_test.go
ui/protocol.go
ui/protocol_test.go
ui/status.go
ui/style.go
ui/utils.go
ui/viewport.go
ui/viewport_test.go

- adds basic viewport and elements
- integrates with existing status methods
- adds version api endpoint for node information
- resolves https://algorandfoundation.atlassian.net/browse/ENG-592

feat: tui application with live status

---

internal/accounts.go
internal/metrics.go
internal/metrics_test.go
internal/state.go
internal/state_test.go

- parses /metrics endpoint
- adds Enabled bool to MetricsModel for when the RPC is not available
- resolves https://algorandfoundation.atlassian.net/browse/ENG-587

feat: metrics RPC endpoint and parser

---

internal/block.go
internal/block_test.go
internal/state.go
internal/status.go

- calculates average round time ever 5th round
- calculates TPS on every block with a rolling window (default 100)
- #6 
- resolves https://algorandfoundation.atlassian.net/browse/ENG-588

feat: TPS and average round times

---

cmd/root.go
internal/block.go
internal/state.go
ui/error.go
ui/style.go
ui/viewport.go

- catches nil transaction counters
- bubbles up errors to the viewport for states like fast-catchup
- relates to https://algorandfoundation.atlassian.net/browse/ENG-567

fix: catchup and zero tc blocks

---

ui/protocol.go
ui/status.go
ui/style.go

- adds classic TUI border titles 
- resolves https://algorandfoundation.atlassian.net/browse/ENG-617

feat: border titles

---

README.md

Added warnings and notes to README regarding the dev/early state of the project

README: Add alpha/dev warnings & notes

---

internal/participation.go
internal/participation_test.go

Lora fee was set to 2A still, removed it

remove 2A fee from lora deep link

---

CONTRIBUTING.md
README.md
install.sh

- updates README to latest changes
- adds install.sh script

docs: update readme to latest

---

.github/workflows/CD.yaml

- builds ARM/AMD64 for *nix and Darwin
- releases v1.0.0-beta.1
- stages for v1.0.0 release

release: v1.0.0-beta.1

---

internal/state.go
internal/status.go

- fixes bug in fast catchup vs sync detection

fix: fast-catchup detection

---

internal/algod/state.go
internal/algod/status.go
internal/algod/status_test.go
ui/modal/controller.go

- adds fast-catchup state to status
- adds fast-catchup to an exception modal

feat: add fast-catchup state to status

---

internal/algod/status.go
ui/app/keys.go
ui/app/modal.go
ui/modal/controller.go
ui/modal/model.go
ui/modal/view.go
ui/modals/info/info.go

- adds prefix message to the Info Modal after account goes online
- adds prefix message to the Info Modal after keys are generated
- coverts online actions to register (O->R)

chore: alert user when going online/generates new key

---

cmd/bootstrap.go
ui/bootstrap/model.go

fix: bootstrap refinements

---

.github/workflows/CD.yaml

release: v1.0.0

---

install.sh

- install.sh offer to replace local nodekit binary
-  windows error to explain WSL requirement and link to docs

feat: install.sh support replacing local nodekit, windows/WSL error more info

---

docs/src/content/docs/guides/getting-started.mdx

Added OS icons to the getting started page

Docs: add OS icons in getting started page

---

cmd/debug.go

- truncates token in debug command
- resolves https://algorandfoundation.atlassian.net/browse/ENG-705

chore: truncate token in debug command

---

internal/system/cmds.go

- changes position of logger to alert the user earlier

chore: move logger to top of cmd loop

---

docs/astro.config.mjs
docs/src/pages/index.astro

- Fixed landing page width to not overflow on mobile
- Remove stale link from sidebar
- Add source + issues links to sidebar

Docs: responsive landing page

---

.github/workflows/CD.yaml

- fixes upload workflow for empty releases

cd: skip upload when there is no version

---

.github/ISSUE_TEMPLATE/💄-ui-improvement.md

- adds ui improvement issue template

chore: add ui improvement template

---

ui/bootstrap/model.go

- uses autostyle for bootstrap questions
- resolves #93

chore: use autostyle for bootstrap questions

---

internal/algod/state.go

- reorganizes participation key fetching to be up front.
- resolves #112

chore: improve active key detection

---

internal/algod/mac/mac.go

- adds brew update to darwin upgrade
- restarts service after upgrade
- resolves #100

fix: add update for brew

---

ui/modal/model.go

- remove active from set suspended

fix: remove active from SetSuspended

---

ui/modal/controller.go
ui/modal/model.go
ui/modals/transaction/model.go

- keyreg offline detection 
- QR enabled for testnet/mainnet only
-  suspended state reset

Fix: keyreg offline detection, QR enabled for testnet/mainnet, suspended state reset

---

ui/modals/transaction/model.go

Disabling the QR signing for mainnet temporarily until some Pera issues are fixed

fix: disable QRs for mainnet temporarily

---

internal/algod/mac/mac.go

chore: brew clarification

---

docs/src/pages/offline.astro

2 quick fixes based on mobile testing:
- fix NFD searching with uppercase
- fix clearing tips until first search (search scrolls under keyboard on mobile)

docs: fix NFD searching with uppercase, fix clearing tips 

---

docs/src/pages/offline.astro

- Fix z-index & overlapping text issues with header

docs: fix z-index issues

---

cmd/root.go
ui/overlay/controller.go

- ensures the fast catchup modal is toggled properly

fix(overlay): force fast-catchup mode

---

internal/algod/client.go
internal/algod/participation/participation.go

- fixed timeout in wait for node
- added log to inform that we are waiting for node
- fixed timeout in wait for participation key generation
- resolves #164

fix: timeouts: wait for node, wait for key generation

---

cmd/bootstrap.go
internal/algod/mac/mac.go

- deduplicate code in bootstrap

refactor: deduplicate bootstrap code
