algorandfoundation/nodekit

cmd/root.go, internal/state.go, internal/status.go
- sets SYNCING status when CatchupTime is 0
- sets LastRound based on the latest status 
- #7 
- resolves https://algorandfoundation.atlassian.net/browse/ENG-586
=> feat: sync status and latest round

.github/workflows/test.yaml, api/lf.go, generate.yaml, go.mod, internal/accounts.go, internal/accounts_test.go, ui/pages/transaction/controller.go
=> test: internal/accounts.go

cmd/root.go, cmd/root_test.go, internal/block.go, internal/state.go, main_test.go, ui/viewport.go
- adds missing status code handlers
- add wait period after error
=> fix: improve resilience and error handling

internal/metrics.go, internal/state.go, ui/status.go
- calculates RX/TX based on a timestamp window
- adds better display of rate
- resolves https://algorandfoundation.atlassian.net/browse/ENG-618
=> fix: RX/TX display

cmd/root.go, internal/accounts.go, internal/accounts_test.go, internal/state.go, internal/test/client.go, internal/test/mock/fixtures.go, ui/internal/test/state.go, ui/pages/accounts/model.go
- refactors Account.Expires  
- refactors AccountsFromState to be more readable
- adds expired resident and non-resident keys
=> fix: show expired keys

api/github.go, internal/algod/status.go
Fixes crash on fnet nodes because of `dev` release channel lookup on GH.
Would a better approach be to disable lookups entirely when a dev build is found?
=> override github channel dev->beta

cmd/bootstrap.go
- adds early exit to `bootstrap` for invalid systems and prompts to run the TUI manually
- resolves https://algorandfoundation.atlassian.net/browse/ENG-703
=> fix: existing algorand data environment

install.sh
We offer wget as an install command, but install.sh was still using curl internally. Fixed it to fall back to wget if curl is not available
=> Fix: install.sh to test for curl, otherwise use wget

main.go
Disable nodekit upgrade warnings for dev builds
- resolves #117
=> chore: disable nodekit upgrade nag for dev versions

ui/modal/testdata/Test_Snapshot/InfoModal.golden, ui/modals/info/info.go, ui/modals/info/testdata/Test_Snapshot/Visible.golden, ui/utils/utils.go
The key info modal rendered the participation keys with base64url
The expected format is base64 with padding, as goal outputs. This fixes copy-pastability to 3rd party tools that may not support base64url.
=> Fix: participation key rendering from base64url to base64

cmd/bootstrap.go, cmd/root.go, internal/algod/participation/participation.go, internal/algod/state.go, internal/algod/status.go, ui/modals/transaction/controller.go, ui/modals/transaction/view.go
Enables automatic setting of incentive eligibility fees. Users can opt out by running nodekit with `--no-incentives`
Criteria to add the 2A fee:
1) incentives allowed by user - command line flag to disable incentives has _not_ been passed
2) keyreg type if online
3) protocol supports incentives - currently gated to the v4 protocol, can be a list or feature-based in the future.
4) account is not already incentives eligible
=> feat: enable incentive eligibility fees

cmd/utils/flags.go, internal/system/cmds.go
- cleans up command outputs for command runner
- organizes friendly error at the end of command output
- handles multiple error types gracefully
- resolves #106
=> fix: improve command error handling

docs/src/pages/index.astro
Updated landing page docs link to point to the new dev portal node running docs (https://developer.algorand.co/nodes/nodekit-quick-start/)
=> Docs: Changed doc link on landing page to redirect to new dev portal

cmd/bootstrap.go, internal/algod/algod.go, internal/algod/client.go, ui/bootstrap/model.go
Resolves the case when fast-catchup fails due to the node being inaccessible during bootstrap.
- adds wait for client interface
- ensures the service is active before trying to access the node
- uses parameters for fast catchup
=> fix: wait for status from unstable clients

ui/modal/modal_test.go, ui/modals/info/info.go, ui/modals/transaction/controller.go, ui/modals/transaction/model.go, ui/modals/transaction/transaction_test.go, ui/modals/transaction/view.go, ui/viewport.go
- toggles between QR and Lora Link
=> feat: toggle between QRCode and deep-link

internal/algod/participation/participation.go, ui/modal/controller.go, ui/modal/model.go
=> fix: deterministic state while detecting corrupt keys

ui/modals/transaction/controller.go
- fixed race condition in `ShouldAddIncentivesFee`
=> Fix: nil pointer dereference when adding new accounts

docs/src/pages/index.astro, docs/src/pages/offline.astro
Test link: https://docs-keyreg-offline-page.nodekit-run.pages.dev/offline
- Adds a keyreg offline utility for deployment on nodekit.run/off
- This searches account addresses or NFDs and links to Lora for a quick keyreg account
=> Docs: keyreg offline page on nodekit.run/offline

install.sh, unattended.sh
Introduces the `NODEKIT_FORCE_INSTALL` and `NODEKIT_SKIP_BOOTSTRAP` environment variables to the installer. These are considered enabled if they are set to any non-zero-length string.
`NODEKIT_FORCE_INSTALL` - replace existing nodekit without prompting
`NODEKIT_SKIP_BOOTSTRAP` - skip the final bootstrap step 
The two can be used to script an unattended installation of nodekit, e.g. with:
`wget -qO- https://nodekit.run/install.sh | NODEKIT_FORCE_INSTALL=1 NODEKIT_SKIP_BOOTSTRAP=1 bash`
Example usage has been added under `unattended.sh`
=> Feat: installer env vars enabling unattended installation

cmd/telemetry/disable/disable.go, cmd/telemetry/enable/enable.go, cmd/telemetry/enable/nodely.go, cmd/telemetry/status.go, cmd/telemetry/telemetry.go
- fix help strings
- `telemetry status` to show dashboard URL if profile matches nodely
- added nodely telemetry docs to `telemetry enable nodely`
=> Docs: telemetry changes

cmd/debug.go
algod admin token smaller than 3 characters (including empty file) causes panic
- resolves #162
=> fix: debug: fix small token (less than 3 chars) causing panic

internal/algod/linux/linux.go
- detect & error when an `algorand` user exists (with PID >= 1000 i.e. a user-level user, vs. the system-level user we expect which would be < 1000) 
- resolves #71
=> fix: install: error when an algorand user exists

ui/modals/partkey/transaction/controller.go
As Mainnet has now successfully upgraded to a new consensus version, an old check was preventing the 2 Algo fee from being suggested when generating a keyreg transaction for eligible participants.
=> fix: allow any consensus version when determining keyreg fee
